include("solutions.jl")

# println("Day 01: ", day1(open("input_day1.txt")))
# println("Day 02: ", day2(open("input_day2.txt")))
# println("Day 03: ", day3(open("input_day3.txt")))
# println("Day 04: ", day4(open("input_day4.txt")))
# println("Day 06: ", day6(open("input_day6.txt")))
# println("Day 07: ", day7(open("input_day7.txt")))
# println("Day 08: ", day8(open("input_day8.txt")))
# println("Day 09: ", day9(open("input_day9.txt")))
# println("Day 10: ", day10(open("input_day10.txt")))
# println("Day 11: ", day11(open("input_day11.txt")))
println("Day 12: ", day12(open("test_day12.txt")))
